### ISSUE TITLE
error while loading shared libraries: libnss3.so

### ISSUE THREAD

**Issue by matthewmueller** [aheuermann/docker-electron#1]
Hi there. I'm not sure of the state of this Dockerfile, but I'm running into the following error:

```
/usr/local/lib/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
```

While following the instructions here: https://github.com/maxogden/electron-spawn

Any ideas?

**Comment by aheuermann** [comment]
It looks like `libnss3` was added as a dependency with electron `0.29.2`.  I updated the dockerfile and also added a basic readme with how I'm running my tests with xvfb. Hope it helps.

**Comment by matthewmueller** [comment]
<3
