### ISSUE TITLE
Update node version

### ISSUE THREAD

**Issue by dominicbarnes** [aheuermann/docker-electron#2]
Just tried to use this and it died on `let` since it's only on node 0.12. Any chance you'd be willing to update to the 4.x stable branch?

**Comment by aheuermann** [comment]
Sorry Dominic, just noticed this. I went ahead and added builds for latest node 4, 5, & 6. 
It may make more sense to just copy the RUN command to your own Dockerfile though so that you can be more specific with node versioning.
